name = "cloud-mail"
main = "src/index.js"
compatibility_date = "2025-04-09"
keep_vars = true

[observability]
enabled = true

#[[d1_databases]]
#binding = "db"			#d1数据库绑定名默认不可修改
#database_name = "1mail"		#d1数据库名字
#database_id = "9736b056-505b-4f98-8ade-3c9998c53a38"		#d1数据库id

#[[kv_namespaces]]
#binding = "kv"			#kv绑定名默认不可修改
#id = "12a8f7a42b6444ad87ee823a2c6532b8"					#kv数据库id

#[[r2_buckets]]
#binding = "r2"			#r2对象存储绑定名默认不可修改
#bucket_name = "cloud-mail-r2"		#r2对象存储桶的名字

[assets]
binding = "assets"		#静态资源绑定名默认不可修改
directory = "./dist"	#前端vue项目打包的静态资源存放位置,默认dist
not_found_handling = "single-page-application"
run_worker_first = true

[triggers]
crons = ["0 16 * * *"]	#定时任务每天晚上12点执行


#[vars]
#orm_log = false
#domain = []				#邮件域名可可配置多个 示例: ["example1.com","example2.com"]
#admin = ""				#管理员的邮箱	示例: admin@example.com
#jwt_secret = ""			#jwt令牌的密钥,随便填一串字符串
